Update pat.md to add configuration instructions
hacs/documentation pull request #181
Opened 2021-06-06 19:14 UTC by beirtipol

Add instructions about placing the token in the config file! These instructions are available on other pages but it makes sense to include them in the step-by-step guide?

2021-06-06 19:20 UTC, ludeeus requested changes
This will add duplicate information in two different places that needs to be kept in sync, options:
- just reference the main config
- link to main config

2021-06-06 19:27 UTC, beirtipol commented
Which page should it link to? I'm struggling finding the page again that I originally saw it on. Seems like the 'pat' information should all be in one place as the only time you would edit the token in configuration.yml is after you generate a new one?

2021-06-07 09:18 UTC, ludeeus commented
https://hacs.xyz/docs/configuration/legacy

2021-06-07 09:43 UTC, ludeeus commented on documentation/configuration/pat.md
> +Follow the instructions [here](legacy.md) to add the token to the Hassio configuration.yml
```suggestion
Follow the [instructions here](legacy.md) to add the token to the Home Assistant configuration
```

"hassio" has not existed in almost 2 years

2021-06-07 11:23 UTC, ludeeus approved these changes

2021-06-07 11:24 UTC, merged